application: ciftsarmalnews
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: templates/favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: templates/css

- url: /js
  static_dir: templates/js

- url: /fonts
  static_dir: templates/fonts

- url: /icons
  static_dir: templates/icons

- url: /tasks/.*
  script: tasks.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
